"use client"

import { useState, useEffect, useRef } from "react"
import {
  Activity,
  TrendingUp,
  MapPin,
  AlertTriangle,
  Phone,
  Search,
  Filter,
  Plus,
  X,
  Check,
  Clock,
  Star,
  Heart,
  Shield,
  Truck,
  Home,
  Route,
  Package,
  UserCheck,
} from "lucide-react"

// Enhanced mock data for water level monitoring
const waterStations = [
  {
    id: "station-a",
    name: "River Station A",
    location: "Downtown Bridge",
    currentLevel: 8.5,
    status: "critical",
    lat: 40.7128,
    lng: -74.006,
    normalLevel: 3.2,
    warningLevel: 6.0,
    criticalLevel: 8.0,
    capacity: 10.0,
    trend: "rising",
    lastUpdated: "2 min ago",
  },
  {
    id: "station-b",
    name: "River Station B",
    location: "Central Park Area",
    currentLevel: 6.2,
    status: "warning",
    lat: 40.7589,
    lng: -73.9851,
    normalLevel: 2.8,
    warningLevel: 5.5,
    criticalLevel: 7.5,
    capacity: 9.0,
    trend: "stable",
    lastUpdated: "1 min ago",
  },
  {
    id: "station-c",
    name: "River Station C",
    location: "Industrial District",
    currentLevel: 4.1,
    status: "normal",
    lat: 40.6892,
    lng: -74.0445,
    normalLevel: 3.0,
    warningLevel: 5.0,
    criticalLevel: 7.0,
    capacity: 8.5,
    trend: "falling",
    lastUpdated: "3 min ago",
  },
]

// Historical data for charts
const generateHistoricalData = (stationId) => {
  const baseLevel = waterStations.find((s) => s.id === stationId)?.currentLevel || 5
  return Array.from({ length: 24 }, (_, i) => ({
    time: `${23 - i}:00`,
    level: Math.max(0, baseLevel + (Math.random() - 0.5) * 2),
    rainfall: Math.random() * 10,
  }))
}

// Enhanced alert system with more comprehensive data
const alertTypes = [
  { value: "critical", label: "Critical", color: "destructive" },
  { value: "warning", label: "Warning", color: "chart-5" },
  { value: "info", label: "Information", color: "primary" },
  { value: "resolved", label: "Resolved", color: "secondary" },
]

const alertCategories = [
  { value: "flood", label: "Flood Warning" },
  { value: "evacuation", label: "Evacuation" },
  { value: "infrastructure", label: "Infrastructure" },
  { value: "weather", label: "Weather" },
  { value: "emergency", label: "Emergency" },
]

const mockAlertsEnhanced = [
  {
    id: 1,
    type: "critical",
    category: "flood",
    title: "Flash Flood Warning",
    message: "Immediate flash flood warning for downtown area. Water levels rising rapidly at Station A.",
    location: "Downtown District",
    station: "Station A",
    time: "2 min ago",
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    status: "active",
    acknowledged: false,
    acknowledgedBy: null,
    priority: 1,
    affectedAreas: ["Downtown", "Business District", "Riverside"],
    estimatedImpact: "High",
    responseTeams: ["Fire Department", "Emergency Services"],
    autoGenerated: true,
  },
  {
    id: 2,
    type: "warning",
    category: "flood",
    title: "Rising Water Levels",
    message: "Water levels at Station A have exceeded warning threshold. Monitor closely for potential evacuation.",
    location: "River Station A",
    station: "Station A",
    time: "15 min ago",
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    status: "active",
    acknowledged: true,
    acknowledgedBy: "John Smith",
    priority: 2,
    affectedAreas: ["Riverside"],
    estimatedImpact: "Medium",
    responseTeams: ["Flood Control"],
    autoGenerated: true,
  },
  {
    id: 3,
    type: "info",
    category: "evacuation",
    title: "Evacuation Route Update",
    message: "Evacuation route B is now clear and operational. All residents can use this route safely.",
    location: "Route B - Eastern District",
    station: null,
    time: "1 hour ago",
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    status: "active",
    acknowledged: true,
    acknowledgedBy: "Sarah Johnson",
    priority: 3,
    affectedAreas: ["Eastern District"],
    estimatedImpact: "Low",
    responseTeams: ["Traffic Control"],
    autoGenerated: false,
  },
  {
    id: 4,
    type: "resolved",
    category: "infrastructure",
    title: "Power Restoration Complete",
    message: "Power has been fully restored to the affected areas. All emergency systems are operational.",
    location: "Industrial District",
    station: null,
    time: "2 hours ago",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: "resolved",
    acknowledged: true,
    acknowledgedBy: "Mike Davis",
    priority: 2,
    affectedAreas: ["Industrial District"],
    estimatedImpact: "Medium",
    responseTeams: ["Utility Company"],
    autoGenerated: false,
  },
]

const emergencyContactsEnhanced = [
  {
    id: 1,
    name: "Emergency Services",
    role: "Fire Department",
    contact: "911",
    priority: 1,
    department: "Fire & Rescue",
    availability: "24/7",
    responseTime: "5-8 minutes",
    serviceArea: "Citywide",
    specialties: ["Fire suppression", "Water rescue", "Emergency medical"],
    protocols: "Immediate response for flood emergencies",
    favorite: true,
  },
  {
    id: 2,
    name: "Flood Control Center",
    role: "Water Management",
    contact: "(555) 123-4567",
    priority: 1,
    department: "Public Works",
    availability: "24/7",
    responseTime: "10-15 minutes",
    serviceArea: "Metropolitan area",
    specialties: ["Water level monitoring", "Dam operations", "Flood barriers"],
    protocols: "Coordinate with emergency services for evacuations",
    favorite: true,
  },
  {
    id: 3,
    name: "Emergency Management",
    role: "Disaster Coordination",
    contact: "(555) 234-5678",
    priority: 1,
    department: "Emergency Management",
    availability: "24/7",
    responseTime: "Immediate",
    serviceArea: "Regional",
    specialties: ["Evacuation coordination", "Resource allocation", "Public alerts"],
    protocols: "Central command for all disaster response",
    favorite: false,
  },
  {
    id: 4,
    name: "Red Cross Emergency",
    role: "Humanitarian Aid",
    contact: "(555) 345-6789",
    priority: 2,
    department: "Non-profit",
    availability: "24/7",
    responseTime: "30-60 minutes",
    serviceArea: "Regional",
    specialties: ["Emergency shelter", "Food distribution", "Medical aid"],
    protocols: "Support evacuation centers and displaced persons",
    favorite: true,
  },
  {
    id: 5,
    name: "National Weather Service",
    role: "Weather Monitoring",
    contact: "(555) 456-7890",
    priority: 2,
    department: "Federal",
    availability: "24/7",
    responseTime: "Real-time updates",
    serviceArea: "Regional",
    specialties: ["Weather forecasting", "Flood warnings", "Storm tracking"],
    protocols: "Issue weather alerts and flood warnings",
    favorite: false,
  },
  {
    id: 6,
    name: "Police Emergency",
    role: "Law Enforcement",
    contact: "911",
    priority: 1,
    department: "Police",
    availability: "24/7",
    responseTime: "3-5 minutes",
    serviceArea: "Citywide",
    specialties: ["Traffic control", "Evacuation enforcement", "Security"],
    protocols: "Secure evacuation routes and maintain order",
    favorite: false,
  },
  {
    id: 7,
    name: "Utility Emergency",
    role: "Power & Water",
    contact: "(555) 567-8901",
    priority: 2,
    department: "Utilities",
    availability: "24/7",
    responseTime: "15-30 minutes",
    serviceArea: "Service territory",
    specialties: ["Power restoration", "Water system", "Gas safety"],
    protocols: "Shut off utilities in flood zones",
    favorite: false,
  },
  {
    id: 8,
    name: "Hospital Emergency",
    role: "Medical Services",
    contact: "(555) 678-9012",
    priority: 1,
    department: "Healthcare",
    availability: "24/7",
    responseTime: "Immediate",
    serviceArea: "Regional",
    specialties: ["Emergency medicine", "Trauma care", "Patient evacuation"],
    protocols: "Prepare for flood-related injuries and evacuations",
    favorite: true,
  },
  {
    id: 9,
    name: "Transportation Authority",
    role: "Transit Operations",
    contact: "(555) 789-0123",
    priority: 2,
    department: "Transportation",
    availability: "Business hours",
    responseTime: "20-45 minutes",
    serviceArea: "Transit network",
    specialties: ["Public transit", "Road closures", "Alternative routes"],
    protocols: "Coordinate evacuation transportation",
    favorite: false,
  },
  {
    id: 10,
    name: "Animal Control",
    role: "Animal Rescue",
    contact: "(555) 890-1234",
    priority: 3,
    department: "Animal Services",
    availability: "Extended hours",
    responseTime: "45-90 minutes",
    serviceArea: "County",
    specialties: ["Animal rescue", "Pet sheltering", "Wildlife management"],
    protocols: "Rescue and shelter animals during evacuations",
    favorite: false,
  },
  {
    id: 11,
    name: "Salvation Army",
    role: "Emergency Relief",
    contact: "(555) 901-2345",
    priority: 2,
    department: "Non-profit",
    availability: "Extended hours",
    responseTime: "60-120 minutes",
    serviceArea: "Regional",
    specialties: ["Emergency shelter", "Food service", "Disaster relief"],
    protocols: "Provide long-term support for displaced residents",
    favorite: false,
  },
]

// ADDED: New data for the Protocols tab
const emergencyProtocols = {
  normal: [
    "Monitor all water level stations every 6 hours.",
    "Ensure all communication systems are online and tested weekly.",
    "Review and update emergency contact lists quarterly.",
    "Conduct monthly checks on flood barrier equipment.",
  ],
  warning: [
    "Increase water level monitoring frequency to every hour.",
    "Alert Priority 2 and relevant municipal contacts.",
    "Place emergency response teams on standby.",
    "Prepare public notification drafts for potential evacuation orders.",
    "Verify all evacuation routes are clear and accessible.",
  ],
  critical: [
    "Activate the Emergency Operations Center (EOC).",
    "Issue immediate evacuation orders for designated high-risk zones.",
    "Deploy all Priority 1 emergency response teams.",
    "Initiate real-time public alerts via all available channels.",
    "Close all major roads and bridges in affected areas.",
  ],
}

export default function FloodManagementApp() {
  const [activeTab, setActiveTab] = useState("dashboard")
  const [selectedStation, setSelectedStation] = useState("station-a")
  const [currentTime, setCurrentTime] = useState(new Date())
  const [historicalData, setHistoricalData] = useState({})

  const [alerts, setAlerts] = useState(mockAlertsEnhanced)
  const [alertFilter, setAlertFilter] = useState("all")
  const [alertSort, setAlertSort] = useState("newest")
  const [showCreateAlert, setShowCreateAlert] = useState(false)
  const [newAlert, setNewAlert] = useState({
    type: "info",
    category: "flood",
    title: "",
    message: "",
    location: "",
    priority: 3,
    affectedAreas: "",
    estimatedImpact: "Low",
  })

  const [contacts, setContacts] = useState(emergencyContactsEnhanced)
  const [contactSearch, setContactSearch] = useState("")
  const [contactFilter, setContactFilter] = useState("all")
  const [contactSort, setContactSort] = useState("priority")
  const [showContactDetails, setShowContactDetails] = useState(null)
  const [favoriteContacts, setFavoriteContacts] = useState(new Set([1, 2, 4, 8]))

  const [isWorldWindLoaded, setIsWorldWindLoaded] = useState(false)
  const worldWindRef = useRef(null)

  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000)
    return () => clearInterval(timer)
  }, [])

  useEffect(() => {
    // Generate historical data for all stations
    const data = {}
    waterStations.forEach((station) => {
      data[station.id] = generateHistoricalData(station.id)
    })
    setHistoricalData(data)
  }, [])

  useEffect(() => {
    if (typeof window !== "undefined") {
      const checkWorldWind = () => {
        if (typeof window.WorldWind !== "undefined") {
          console.log("[v0] WorldWind library already available")
          setIsWorldWindLoaded(true)
        } else {
          // Load the stable version from the refined implementation
          const script = document.createElement("script")
          script.src = "https://unpkg.com/@nasaworldwind/worldwind@0.9.0/build/dist/worldwind.min.js"
          script.async = true
          script.onload = () => {
            console.log("[v0] WorldWind library loaded successfully")
            setIsWorldWindLoaded(true)
          }
          script.onerror = (error) => {
            console.error("[v0] Failed to load WorldWind library:", error)
            setIsWorldWindLoaded(false)
          }
          document.head.appendChild(script)
        }
      }

      checkWorldWind()
    }
  }, [])

  useEffect(() => {
    if (!isWorldWindLoaded || activeTab !== "dashboard") return

    const initializeWorldWind = () => {
      const canvas = document.getElementById("worldwind-canvas")
      if (!canvas) {
        console.error("[v0] Canvas element not found, retrying...")
        setTimeout(initializeWorldWind, 200)
        return
      }

      try {
        console.log("[v0] Initializing WorldWind with canvas:", canvas)

        if (!window.WorldWind || !window.WorldWind.WorldWindow) {
          console.error("[v0] WorldWind library not properly loaded")
          return
        }

        // Create WorldWindow with error handling
        let wwd
        try {
          wwd = new window.WorldWind.WorldWindow("worldwind-canvas")
        } catch (wwdError) {
          console.error("[v0] Failed to create WorldWindow:", wwdError)
          // Try alternative initialization approach
          try {
            wwd = new window.WorldWind.WorldWindow(canvas)
          } catch (altError) {
            console.error("[v0] Alternative WorldWindow creation also failed:", altError)
            return
          }
        }

        if (!wwd) {
          console.error("[v0] WorldWindow creation failed")
          return
        }

        const layerConfigs = [
          { name: "BMNGOneImageLayer", enabled: true },
          { name: "BingAerialWithLabelsLayer", enabled: true },
          { name: "CompassLayer", enabled: true },
        ]

        layerConfigs.forEach((config) => {
          try {
            if (window.WorldWind[config.name]) {
              const layer = new window.WorldWind[config.name]()
              layer.enabled = config.enabled
              wwd.addLayer(layer)
            }
          } catch (layerError) {
            console.warn(`[v0] Failed to add layer ${config.name}:`, layerError)
          }
        })

        try {
          const riskLayer = new window.WorldWind.RenderableLayer("Flood Risk Zones")
          wwd.addLayer(riskLayer)

          // High-risk zone (red) - Kedarnath area
          if (window.WorldWind.SurfacePolygon && window.WorldWind.ShapeAttributes) {
            const highRiskAttributes = new window.WorldWind.ShapeAttributes(null)
            highRiskAttributes.interiorColor = new window.WorldWind.Color(1, 0, 0, 0.6)
            highRiskAttributes.outlineColor = new window.WorldWind.Color(1, 0, 0, 1)
            highRiskAttributes.drawInterior = true
            highRiskAttributes.drawOutline = true

            const highRiskBoundaries = [
              new window.WorldWind.Position(30.735, 79.064, 100),
              new window.WorldWind.Position(30.736, 79.065, 100),
              new window.WorldWind.Position(30.735, 79.066, 100),
              new window.WorldWind.Position(30.734, 79.065, 100),
            ]
            const highRiskPolygon = new window.WorldWind.SurfacePolygon(highRiskBoundaries, highRiskAttributes)
            riskLayer.addRenderable(highRiskPolygon)

            // Low-risk zone (green)
            const lowRiskAttributes = new window.WorldWind.ShapeAttributes(null)
            lowRiskAttributes.interiorColor = new window.WorldWind.Color(0, 1, 0, 0.6)
            lowRiskAttributes.outlineColor = new window.WorldWind.Color(0, 1, 0, 1)
            lowRiskAttributes.drawInterior = true
            lowRiskAttributes.drawOutline = true

            const lowRiskBoundaries = [
              new window.WorldWind.Position(30.737, 79.068, 100),
              new window.WorldWind.Position(30.738, 79.069, 100),
              new window.WorldWind.Position(30.737, 79.07, 100),
              new window.WorldWind.Position(30.736, 79.069, 100),
            ]
            const lowRiskPolygon = new window.WorldWind.SurfacePolygon(lowRiskBoundaries, lowRiskAttributes)
            riskLayer.addRenderable(lowRiskPolygon)
          }

          const kedarnathStations = [
            { name: "Kedarnath Temple", lat: 30.735, lng: 79.066, level: "2.1m" },
            { name: "Mandakini River", lat: 30.74, lng: 79.07, level: "3.8m" },
            { name: "Gaurikund", lat: 30.72, lng: 79.055, level: "1.9m" },
          ]

          kedarnathStations.forEach((station) => {
            try {
              const placemark = new window.WorldWind.Placemark(
                new window.WorldWind.Position(station.lat, station.lng, 100),
              )
              placemark.label = `${station.name}\n${station.level}`
              placemark.altitudeMode = window.WorldWind.RELATIVE_TO_GROUND
              riskLayer.addRenderable(placemark)
            } catch (placemarkError) {
              console.warn(`[v0] Failed to create placemark for ${station.name}:`, placemarkError)
            }
          })
        } catch (riskLayerError) {
          console.warn("[v0] Failed to create risk layer:", riskLayerError)
        }

        try {
          wwd.goTo(new window.WorldWind.Position(30.735, 79.066, 10000))
        } catch (navError) {
          console.warn("[v0] Failed to navigate to Kedarnath:", navError)
        }

        console.log("[v0] WorldWind initialization completed successfully")
      } catch (error) {
        console.error("[v0] Critical error during WorldWind initialization:", error)
        const canvas = document.getElementById("worldwind-canvas")
        if (canvas) {
          const ctx = canvas.getContext("2d")
          if (ctx) {
            ctx.fillStyle = "#f3f4f6"
            ctx.fillRect(0, 0, canvas.width, canvas.height)
            ctx.fillStyle = "#374151"
            ctx.font = "16px Arial"
            ctx.textAlign = "center"
            ctx.fillText("3D Map temporarily unavailable", canvas.width / 2, canvas.height / 2)
            ctx.fillText("Please refresh the page", canvas.width / 2, canvas.height / 2 + 25)
          }
        }
      }
    }

    const timer = setTimeout(initializeWorldWind, 100)
    return () => clearTimeout(timer)
  }, [isWorldWindLoaded, activeTab])

  const getStatusColor = (status) => {
    switch (status) {
      case "critical":
        return "bg-destructive text-destructive-foreground"
      case "warning":
        return "bg-chart-5 text-foreground"
      case "normal":
        return "bg-primary text-primary-foreground"
      default:
        return "bg-muted text-muted-foreground"
    }
  }

  const getAlertColor = (type) => {
    switch (type) {
      case "critical":
        return "border-destructive bg-destructive/10"
      case "warning":
        return "border-chart-5 bg-chart-5/10"
      case "info":
        return "border-primary bg-primary/10"
      case "resolved":
        return "border-secondary bg-secondary/10"
      default:
        return "border-border"
    }
  }

  const getTrendIcon = (trend) => {
    switch (trend) {
      case "rising":
        return <TrendingUp className="h-4 w-4 text-destructive" />
      case "falling":
        return <TrendingUp className="h-4 w-4 text-primary rotate-180" />
      case "stable":
        return <Activity className="h-4 w-4 text-muted-foreground" />
      default:
        return null
    }
  }

  const calculateProgress = (current, capacity) => {
    return Math.min((current / capacity) * 100, 100)
  }

  const selectedStationData = waterStations.find((s) => s.id === selectedStation)

  const getAlertStats = () => {
    const active = alerts.filter((a) => a.status === "active")
    const critical = active.filter((a) => a.type === "critical").length
    const warning = active.filter((a) => a.type === "warning").length
    const info = active.filter((a) => a.type === "info").length
    const unacknowledged = active.filter((a) => !a.acknowledged).length

    return { total: active.length, critical, warning, info, unacknowledged }
  }

  const filteredAlerts = alerts
    .filter((alert) => {
      if (alertFilter === "all") return true
      if (alertFilter === "unacknowledged") return !alert.acknowledged && alert.status === "active"
      if (alertFilter === "active") return alert.status === "active"
      return alert.type === alertFilter
    })
    .sort((a, b) => {
      if (alertSort === "newest") return b.timestamp.getTime() - a.timestamp.getTime()
      if (alertSort === "oldest") return a.timestamp.getTime() - b.timestamp.getTime()
      if (alertSort === "priority") return a.priority - b.priority
      return 0
    })

  const acknowledgeAlert = (alertId) => {
    setAlerts((prev) =>
      prev.map((alert) =>
        alert.id === alertId ? { ...alert, acknowledged: true, acknowledgedBy: "Current User" } : alert,
      ),
    )
  }

  const resolveAlert = (alertId) => {
    setAlerts((prev) =>
      prev.map((alert) => (alert.id === alertId ? { ...alert, status: "resolved", type: "resolved" } : alert)),
    )
  }

  const createAlert = () => {
    const alert = {
      id: Date.now(),
      ...newAlert,
      time: "Just now",
      timestamp: new Date(),
      status: "active",
      acknowledged: false,
      acknowledgedBy: null,
      affectedAreas: newAlert.affectedAreas.split(",").map((s) => s.trim()),
      responseTeams: [],
      autoGenerated: false,
      station: null,
    }

    setAlerts((prev) => [alert, ...prev])
    setNewAlert({
      type: "info",
      category: "flood",
      title: "",
      message: "",
      location: "",
      priority: 3,
      affectedAreas: "",
      estimatedImpact: "Low",
    })
    setShowCreateAlert(false)
  }

  const toggleFavorite = (contactId) => {
    setFavoriteContacts((prev) => {
      const newFavorites = new Set(prev)
      if (newFavorites.has(contactId)) {
        newFavorites.delete(contactId)
      } else {
        newFavorites.add(contactId)
      }
      return newFavorites
    })
  }

  const filteredContacts = contacts
    .filter((contact) => {
      const matchesSearch =
        contact.name.toLowerCase().includes(contactSearch.toLowerCase()) ||
        contact.role.toLowerCase().includes(contactSearch.toLowerCase()) ||
        contact.department.toLowerCase().includes(contactSearch.toLowerCase())

      if (!matchesSearch) return false

      if (contactFilter === "all") return true
      if (contactFilter === "favorites") return favoriteContacts.has(contact.id)
      if (contactFilter === "high") return contact.priority === 1
      if (contactFilter === "medium") return contact.priority === 2
      return contact.priority === 3
    })
    .sort((a, b) => {
      if (contactSort === "priority") return a.priority - b.priority
      if (contactSort === "name") return a.name.localeCompare(b.name)
      if (contactSort === "role") return a.role.localeCompare(b.role)
      if (contactSort === "department") return a.department.localeCompare(b.department)
      return 0
    })

  const alertStats = getAlertStats()

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto p-6">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-foreground mb-2">Flood Disaster Management System</h1>
          <p className="text-muted-foreground">Real-time monitoring and emergency response coordination</p>
          <div className="text-sm text-muted-foreground mt-2">Last updated: {currentTime.toLocaleString()}</div>
        </div>

        {/* Navigation Tabs */}
        <div className="flex flex-wrap gap-2 mb-6 border-b">
          {[
            { id: "dashboard", label: "Dashboard", icon: MapPin },
            { id: "water-levels", label: "Water Levels", icon: Activity },
            { id: "alerts", label: "Alerts", icon: AlertTriangle },
            { id: "contacts", label: "Emergency Contacts", icon: Phone },
            { id: "protocols", label: "Protocols", icon: UserCheck },
            { id: "impact", label: "Impact Assessment", icon: Shield },
            { id: "resources", label: "Resources", icon: Package },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2 rounded-t-lg transition-colors ${
                activeTab === tab.id
                  ? "bg-primary text-primary-foreground border-b-2 border-primary"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted"
              }`}
            >
              <tab.icon className="h-4 w-4" />
              {tab.label}
            </button>
          ))}
        </div>

        {/* Dashboard Tab */}
        {activeTab === "dashboard" && (
          <div className="space-y-6">
            {/* Overview Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="bg-card p-6 rounded-lg border">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Active Alerts</p>
                    <p className="text-2xl font-bold text-foreground">{alertStats.total}</p>
                  </div>
                  <AlertTriangle className="h-8 w-8 text-chart-5" />
                </div>
              </div>
              <div className="bg-card p-6 rounded-lg border">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Critical Stations</p>
                    <p className="text-2xl font-bold text-destructive">
                      {waterStations.filter((s) => s.status === "critical").length}
                    </p>
                  </div>
                  <Activity className="h-8 w-8 text-destructive" />
                </div>
              </div>
              <div className="bg-card p-6 rounded-lg border">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Emergency Contacts</p>
                    <p className="text-2xl font-bold text-foreground">{contacts.length}</p>
                  </div>
                  <Phone className="h-8 w-8 text-primary" />
                </div>
              </div>
              <div className="bg-card p-6 rounded-lg border">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Affected Areas</p>
                    <p className="text-2xl font-bold text-foreground">3</p>
                  </div>
                  <MapPin className="h-8 w-8 text-chart-3" />
                </div>
              </div>
            </div>

            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Interactive Flood Risk Map</h3>
              <div className="h-96 bg-muted rounded-lg relative overflow-hidden">
                {isWorldWindLoaded ? (
                  <canvas
                    id="worldwind-canvas"
                    ref={worldWindRef}
                    className="w-full h-full"
                    style={{ width: "100%", height: "100%" }}
                  />
                ) : (
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-2"></div>
                      <p className="text-muted-foreground">Loading NASA WorldWind 3D Map...</p>
                    </div>
                  </div>
                )}

                {/* Map Legend */}
                <div className="absolute top-4 right-4 bg-background/90 backdrop-blur-sm p-3 rounded-lg border">
                  <h4 className="font-semibold text-sm mb-2">Risk Zones</h4>
                  <div className="space-y-1 text-xs">
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 bg-destructive rounded"></div>
                      <span>High Risk</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 bg-chart-5 rounded"></div>
                      <span>Medium Risk</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 bg-primary rounded"></div>
                      <span>Water Stations</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Quick Stats */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-card p-6 rounded-lg border">
                <h3 className="text-lg font-semibold mb-4">Recent Alerts</h3>
                <div className="space-y-3">
                  {alerts.slice(0, 3).map((alert) => (
                    <div key={alert.id} className={`p-3 rounded-lg border ${getAlertColor(alert.type)}`}>
                      <div className="flex items-start justify-between">
                        <div>
                          <p className="font-medium text-sm">{alert.title}</p>
                          <p className="text-xs text-muted-foreground">
                            {alert.location} • {alert.time}
                          </p>
                        </div>
                        <span className={`px-2 py-1 rounded text-xs font-medium ${getStatusColor(alert.type)}`}>
                          {alert.type}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-card p-6 rounded-lg border">
                <h3 className="text-lg font-semibold mb-4">Station Status</h3>
                <div className="space-y-3">
                  {waterStations.map((station) => (
                    <div key={station.id} className="flex items-center justify-between p-3 bg-muted rounded-lg">
                      <div>
                        <p className="font-medium text-sm">{station.name}</p>
                        <p className="text-xs text-muted-foreground">{station.location}</p>
                      </div>
                      <div className="text-right">
                        <p className="font-medium text-sm">{station.currentLevel}m</p>
                        <span className={`px-2 py-1 rounded text-xs font-medium ${getStatusColor(station.status)}`}>
                          {station.status}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Water Levels Tab - keeping existing implementation */}
        {activeTab === "water-levels" && (
          <div className="space-y-6">
            {/* Station Selection */}
            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Water Level Monitoring Stations</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {waterStations.map((station) => (
                  <button
                    key={station.id}
                    onClick={() => setSelectedStation(station.id)}
                    className={`p-4 rounded-lg border text-left transition-colors ${
                      selectedStation === station.id
                        ? "border-primary bg-primary/10"
                        : "border-border hover:border-primary/50"
                    }`}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-medium">{station.name}</h4>
                      {getTrendIcon(station.trend)}
                    </div>
                    <p className="text-sm text-muted-foreground mb-2">{station.location}</p>
                    <div className="flex items-center justify-between">
                      <span className="text-lg font-bold">{station.currentLevel}m</span>
                      <span className={`px-2 py-1 rounded text-xs font-medium ${getStatusColor(station.status)}`}>
                        {station.status}
                      </span>
                    </div>
                    <div className="mt-2">
                      <div className="w-full bg-muted rounded-full h-2">
                        <div
                          className={`h-2 rounded-full ${
                            station.status === "critical"
                              ? "bg-destructive"
                              : station.status === "warning"
                                ? "bg-chart-5"
                                : "bg-primary"
                          }`}
                          style={{ width: `${calculateProgress(station.currentLevel, station.capacity)}%` }}
                        ></div>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">
                        {calculateProgress(station.currentLevel, station.capacity).toFixed(1)}% of capacity
                      </p>
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {/* Selected Station Details */}
            {selectedStationData && (
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div className="bg-card p-6 rounded-lg border">
                  <h3 className="text-lg font-semibold mb-4">Station Details: {selectedStationData.name}</h3>
                  <div className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-sm text-muted-foreground">Current Level</p>
                        <p className="text-2xl font-bold">{selectedStationData.currentLevel}m</p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">Status</p>
                        <span className={`px-3 py-1 rounded font-medium ${getStatusColor(selectedStationData.status)}`}>
                          {selectedStationData.status}
                        </span>
                      </div>
                    </div>

                    <div className="space-y-2">
                      <div className="flex justify-between text-sm">
                        <span>Normal Level:</span>
                        <span>{selectedStationData.normalLevel}m</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span>Warning Level:</span>
                        <span className="text-chart-5">{selectedStationData.warningLevel}m</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span>Critical Level:</span>
                        <span className="text-destructive">{selectedStationData.criticalLevel}m</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span>Maximum Capacity:</span>
                        <span>{selectedStationData.capacity}m</span>
                      </div>
                    </div>

                    <div>
                      <p className="text-sm text-muted-foreground mb-2">Capacity Usage</p>
                      <div className="w-full bg-muted rounded-full h-3">
                        <div
                          className={`h-3 rounded-full ${
                            selectedStationData.status === "critical"
                              ? "bg-destructive"
                              : selectedStationData.status === "warning"
                                ? "bg-chart-5"
                                : "bg-primary"
                          }`}
                          style={{
                            width: `${calculateProgress(selectedStationData.currentLevel, selectedStationData.capacity)}%`,
                          }}
                        ></div>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">
                        {calculateProgress(selectedStationData.currentLevel, selectedStationData.capacity).toFixed(1)}%
                        of maximum capacity
                      </p>
                    </div>

                    <div className="flex items-center gap-2 text-sm">
                      <Clock className="h-4 w-4" />
                      <span>Last updated: {selectedStationData.lastUpdated}</span>
                    </div>
                  </div>
                </div>

                <div className="bg-card p-6 rounded-lg border">
                  <h3 className="text-lg font-semibold mb-4">24-Hour Trend Analysis</h3>
                  <div className="h-64 bg-muted rounded-lg flex items-center justify-center">
                    <p className="text-muted-foreground">Historical trend chart would be displayed here</p>
                  </div>

                  {historicalData[selectedStation] && (
                    <div className="mt-4 space-y-2">
                      <h4 className="font-medium">Recent Readings</h4>
                      <div className="grid grid-cols-3 gap-2 text-xs">
                        {historicalData[selectedStation].slice(-6).map((reading, index) => (
                          <div key={index} className="bg-muted p-2 rounded">
                            <div className="font-medium">{reading.time}</div>
                            <div className="text-muted-foreground">{reading.level.toFixed(1)}m</div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Alerts Tab */}
        {activeTab === "alerts" && (
          <div className="space-y-6">
            {/* Alerts Filter */}
            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Filter Alerts</h3>
              <div className="flex items-center gap-4">
                <div className="flex items-center gap-2">
                  <Filter className="h-4 w-4 text-muted-foreground" />
                  <select
                    value={alertFilter}
                    onChange={(e) => setAlertFilter(e.target.value)}
                    className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                  >
                    <option value="all">All</option>
                    <option value="critical">Critical</option>
                    <option value="warning">Warning</option>
                    <option value="info">Info</option>
                    <option value="unacknowledged">Unacknowledged</option>
                  </select>
                </div>
                <div className="flex items-center gap-2">
                  <Filter className="h-4 w-4 text-muted-foreground" />
                  <select
                    value={alertSort}
                    onChange={(e) => setAlertSort(e.target.value)}
                    className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                  >
                    <option value="newest">Newest</option>
                    <option value="oldest">Oldest</option>
                    <option value="priority">Priority</option>
                  </select>
                </div>
                <button
                  onClick={() => setShowCreateAlert(true)}
                  className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/80"
                >
                  <Plus className="h-4 w-4" />
                  Create Alert
                </button>
              </div>
            </div>

            {/* Alerts List */}
            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Active Alerts</h3>
              <div className="space-y-3">
                {filteredAlerts.map((alert) => (
                  <div key={alert.id} className={`p-3 rounded-lg border ${getAlertColor(alert.type)}`}>
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="font-medium text-sm">{alert.title}</p>
                        <p className="text-xs text-muted-foreground">
                          {alert.location} • {alert.time}
                        </p>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`px-2 py-1 rounded text-xs font-medium ${getStatusColor(alert.type)}`}>
                          {alert.type}
                        </span>
                        {!alert.acknowledged && (
                          <button
                            onClick={() => acknowledgeAlert(alert.id)}
                            className="flex items-center gap-2 px-3 py-1 rounded-lg bg-destructive text-destructive-foreground hover:bg-destructive/80"
                          >
                            <Check className="h-4 w-4" />
                            Acknowledge
                          </button>
                        )}
                        {alert.status === "active" && (
                          <button
                            onClick={() => resolveAlert(alert.id)}
                            className="flex items-center gap-2 px-3 py-1 rounded-lg bg-secondary text-secondary-foreground hover:bg-secondary/80"
                          >
                            <X className="h-4 w-4" />
                            Resolve
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Create Alert Form */}
            {showCreateAlert && (
              <div className="bg-card p-6 rounded-lg border">
                <h3 className="text-lg font-semibold mb-4">Create New Alert</h3>
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Type</label>
                    <select
                      value={newAlert.type}
                      onChange={(e) => setNewAlert({ ...newAlert, type: e.target.value })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    >
                      {alertTypes.map((type) => (
                        <option key={type.value} value={type.value}>
                          {type.label}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Category</label>
                    <select
                      value={newAlert.category}
                      onChange={(e) => setNewAlert({ ...newAlert, category: e.target.value })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    >
                      {alertCategories.map((category) => (
                        <option key={category.value} value={category.value}>
                          {category.label}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Title</label>
                    <input
                      type="text"
                      value={newAlert.title}
                      onChange={(e) => setNewAlert({ ...newAlert, title: e.target.value })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Message</label>
                    <textarea
                      value={newAlert.message}
                      onChange={(e) => setNewAlert({ ...newAlert, message: e.target.value })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Location</label>
           Dt       <input
                      type="text"
                      value={newAlert.location}
                      onChange={(e) => setNewAlert({ ...newAlert, location: e.target.value })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Priority</label>
                    <input
                      type="number"
                      value={newAlert.priority}
                      onChange={(e) => setNewAlert({ ...newAlert, priority: Number.parseInt(e.target.value) })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Affected Areas</label>
                    <input
                      type="text"
                      value={newAlert.affectedAreas}
                      onChange={(e) => setNewAlert({ ...newAlert, affectedAreas: e.target.value })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium text-muted-foreground">Estimated Impact</label>
                    <select
                      value={newAlert.estimatedImpact}
                      onChange={(e) => setNewAlert({ ...newAlert, estimatedImpact: e.target.value })}
                      className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    >
                      <option value="Low">Low</option>
                      <option value="Medium">Medium</option>
                      <option value="High">High</option>
                    </select>
                  </div>
                  <div className="flex items-center justify-end gap-4">
                    <button
                      onClick={() => setShowCreateAlert(false)}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-destructive text-destructive-foreground hover:bg-destructive/80"
                    >
                      <X className="h-4 w-4" />
                      Cancel
                    </button>
                    <button
                      onClick={createAlert}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/80"
                    >
                      <Plus className="h-4 w-4" />
                      Create
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Contacts Tab */}
        {activeTab === "contacts" && (
          <div className="space-y-6">
            {/* Contacts Filter */}
            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Filter Contacts</h3>
              <div className="flex items-center gap-4">
                <div className="flex items-center gap-2">
                  <Search className="h-4 w-4 text-muted-foreground" />
                  <input
                    type="text"
                    value={contactSearch}
                    onChange={(e) => setContactSearch(e.target.value)}
                    className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                    placeholder="Search contacts..."
                  />
                </div>
                <div className="flex items-center gap-2">
                  <Filter className="h-4 w-4 text-muted-foreground" />
                  <select
                    value={contactFilter}
                    onChange={(e) => setContactFilter(e.target.value)}
                    className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                  >
                    <option value="all">All</option>
                    <option value="favorites">Favorites</option>
                    <option value="high">High Priority</option>
                    <option value="medium">Medium Priority</option>
                    <option value="low">Low Priority</option>
                  </select>
                </div>
                <div className="flex items-center gap-2">
                  <Filter className="h-4 w-4 text-muted-foreground" />
                  <select
                    value={contactSort}
                    onChange={(e) => setContactSort(e.target.value)}
                    className="bg-background text-sm text-muted-foreground rounded-lg border px-3 py-2"
                  >
                    <option value="priority">Priority</option>
                    <option value="name">Name</option>
                    <option value="role">Role</option>
                    <option value="department">Department</option>
                  </select>
                </div>
              </div>
            </div>

            {/* Contacts List */}
            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Emergency Contacts</h3>
              <div className="space-y-3">
                {filteredContacts.map((contact) => (
                  <div key={contact.id} className="p-3 rounded-lg border bg-muted">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="font-medium text-sm">{contact.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {contact.role} - {contact.department}
                        </p>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`px-2 py-1 rounded text-xs font-medium bg-primary text-primary-foreground`}>
                          Priority {contact.priority}
                        </span>
                        <button
                          onClick={() => setShowContactDetails(contact.id)}
                          className="flex items-center gap-2 px-3 py-1 rounded-lg bg-primary text-primary-foreground hover:bg-primary/80"
                        >
                          <UserCheck className="h-4 w-4" />
                          Details
                        </button>
                        <button
                          onClick={() => toggleFavorite(contact.id)}
                          className={`flex items-center gap-2 px-3 py-1 rounded-lg ${favoriteContacts.has(contact.id) ? "bg-yellow-500 text-white" : "bg-muted-foreground text-muted"} hover:bg-yellow-500 hover:text-white`}
                        >
                          <Star className="h-4 w-4" />
                          {favoriteContacts.has(contact.id) ? "Favorite" : "Add to Favorites"}
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Contact Details */}
            {showContactDetails && (
              <div className="bg-card p-6 rounded-lg border">
                <h3 className="text-lg font-semibold mb-4">Contact Details</h3>
                <div className="space-y-4">
                  {contacts.find((contact) => contact.id === showContactDetails) && (
                    <div>
                      <p className="text-sm font-medium text-muted-foreground">Name</p>
                      <p className="text-2xl font-bold">
                        {contacts.find((contact) => contact.id === showContactDetails).name}
                      </p>
                    </div>
                  )}
                  {contacts.find((contact) => contact.id === showContactDetails) && (
                    <div>
                      <p className="text-sm font-medium text-muted-foreground">Role</p>
                      <p className="text-2xl font-bold">
                        {contacts.find((contact) => contact.id === showContactDetails).role}
                      </p>
                    </div>
                  )}
                  {contacts.find((contact) => contact.id === showContactDetails) && (
                    <div>
                      <p className="text-sm font-medium text-muted-foreground">Contact</p>
                      <p className="text-2xl font-bold">
                        {contacts.find((contact) => contact.id === showContactDetails).contact}
                      </p>
                    </div>
                  )}
                  <div className="flex items-center justify-end gap-4">
                    <button
                      onClick={() => setShowContactDetails(null)}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-destructive text-destructive-foreground hover:bg-destructive/80"
                    >
                      <X className="h-4 w-4" />
                      Close
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Impact Tab */}
        {activeTab === "impact" && (
          <div className="space-y-6">
            {/* Impact Assessment */}
            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Impact Assessment</h3>
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <Star className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">High Risk Areas</p>
                </div>
                <div className="flex items-center gap-2">
                  <Heart className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Medium Risk Areas</p>
                </div>
                <div className="flex items-center gap-2">
                  <Shield className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Critical Water Stations</p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Resources Tab */}
        {activeTab === "resources" && (
          <div className="space-y-6">
            {/* Resources List */}
            <div className="bg-card p-6 rounded-lg border">
              <h3 className="text-lg font-semibold mb-4">Resources</h3>
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <Truck className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Emergency Vehicles</p>
                </div>
                <div className="flex items-center gap-2">
                  <Home className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Evacuation Shelters</p>
                </div>
                <div className="flex items-center gap-2">
                  <Route className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Evacuation Routes</p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ADDED: Protocols Tab */}
        {activeTab === "protocols" && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Normal Protocols */}
              <div className="bg-card p-6 rounded-lg border">
                <h3 className="text-lg font-semibold mb-4 text-primary">Standard Operating Procedures (Normal)</h3>
                <div className="space-y-3">
                  {emergencyProtocols.normal.map((protocol, index) => (
                    <div key={index} className="flex items-start gap-3">
                      <Check className="h-5 w-5 text-primary mt-1 flex-shrink-0" />
                      <span className="text-muted-foreground text-sm">{protocol}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Warning Protocols */}
              <div className="bg-card p-6 rounded-lg border border-chart-5/50">
                <h3 className="text-lg font-semibold mb-4 text-chart-5">Warning Level Protocols</h3>
                <div className="space-y-3">
                  {emergencyProtocols.warning.map((protocol, index) => (
                    <div key={index} className="flex items-start gap-3">
                      <AlertTriangle className="h-5 w-5 text-chart-5 mt-1 flex-shrink-0" />
                      <span className="text-muted-foreground text-sm">{protocol}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Critical Protocols */}
              <div className="bg-card p-6 rounded-lg border border-destructive/50">
                <h3 className="text-lg font-semibold mb-4 text-destructive">Critical Level Protocols</h3>
                <div className="space-y-3">
                  {emergencyProtocols.critical.map((protocol, index) => (
                    <div key={index} className="flex items-start gap-3">
                      <Shield className="h-5 w-5 text-destructive mt-1 flex-shrink-0" />
                      <span className="text-muted-foreground text-sm font-medium">{protocol}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}